# Input file for Extender
# Each field explained in `run_me.ipynb`

[input]
file_name = "example-methanol-model.bson"
structure = [8, 30, 30, 30, 1]
activations = ["identity", "relu", "relu", "identity"]
use_bias = false
precision = "f64"

[output]
file_name = "output-example-model.bson"
structure = [10, 35, 35, 35, 10, 1]
activations = ["identity", "relu", "relu", "identity", "identity"]
use_bias = true
precision = "f32"

[general]
set_weigths_to = 0.001
test_samples = 10000
