# Input file for NN Extender
# input.structure -- structure of your neural network BEFORE extending
# output.structure -- structure of your neural network AFTER extending

[input]
file_name = "add9-best.bson"
structure = [20, 30, 20, 20, 1]
activations = ["identity", "relu", "relu", "identity"]
bias = true
f64 = true

[output]
file_name ="add9-plus-g3.bson"
structure = [21, 35, 25, 25, 1]
activations = ["identity", "relu", "relu", "identity"]
bias = true
f64 = true

[general]
set_zero_as = 0.01

