# Input file for NN Extender
# input.structure -- structure of your neural network BEFORE extending
# output.structure -- structure of your neural network AFTER extending

[input]
file_name = "model-iter-09.bson"
structure = [11, 30, 20, 20, 1]
activations = ["identity", "relu", "relu", "identity"]
bias = true
f64 = true

[output]
file_name ="water-add-three-g2.bson"
structure = [14, 30, 20, 20, 1]
activations = ["identity", "relu", "relu", "identity"]
bias = true
f64 = true

[general]
set_zero_as = 0.01

