# Input file for NN Extender
# input.structure -- structure of your neural network BEFORE extending
# output.structure -- structure of your neural network AFTER extending

[input]
structure = [8, 20, 20, 20, 1]
activations = ["identity", "relu", "relu", "identity"]

[output]
structure = [12, 30, 30, 30, 1]
activations = ["identity", "relu", "relu", "identity"]
